package com.konsonx.dao;
import com.konsonx.po.Location;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository("LocationMapper")
public interface LocationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer location_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated
     */
    int insert(Location record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated
     */
    int insertSelective(Location record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated
     */
    Location selectByPrimaryKey(Integer location_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Location record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Location record);

    List<Location> findbyLocation_cityandlocation_districtandlocation_addresscontaining(@Param("location_city")String location_city,@Param("location_district")String location_district,@Param("containingLocation_address")String containingLocation_address);

    List<Location> findbylocation_aliascontaining(@Param("containingLocation_alias")String containingLocation_alias);

    List<Location> findorderBylocation_id();

    List<Location> findorderBylocation_iddesc();

    Location findOneByLocation_idForUpdate(Integer location_id);

    Location findOnebyLocation_yun_id(Integer yun_id);
}