package com.konsonx.dao;

import com.konsonx.po.Order;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository("OrderMapper")
public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("order_id") Integer order_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    Order selectByPrimaryKey(@Param("order_id") Integer order_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Order record);

    List<Order> findorderByOrder_create_time();
    List<Order> findorderByOrder_create_timedesc();
    List<Order> findbyOrder_lent_location_idandorder_revert_location_idandorder_user_idOrderbyOrder_create_timedesc(@Param("order_lent_location_id")Integer order_lent_location_id,@Param("order_revert_location_id")Integer order_revert_location_id,@Param("order_user_id")Integer order_user_id);
    Order findFirstbyOrder_user_idandorder_has_finished(@Param("order_user_id")Integer order_user_id,@Param("order_has_finished")Integer order_has_finished);


}