package com.konsonx.dao;
import com.konsonx.po.Pobk;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository("PobkMapper")
public interface PobkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pobk
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer pobk_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pobk
     *
     * @mbg.generated
     */
    int insert(Pobk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pobk
     *
     * @mbg.generated
     */
    int insertSelective(Pobk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pobk
     *
     * @mbg.generated
     */
    Pobk selectByPrimaryKey(Integer pobk_id);
    Pobk selectByPrimaryKeyForUpdate(Integer pobk_id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pobk
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Pobk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pobk
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Pobk record);


    List<Pobk> findbyPobk_location_id(@Param("pobk_location_id") Integer pobk_location_id);

    List<Pobk> findorderByPobk_iddesc();


    /**
     *
     * @param pobk_location_id
     * @param pobk_status 'lent','available',null
     * @return
     */
    List<Pobk> findbyPobk_location_idandpobk_status(@Param("pobk_location_id")Integer pobk_location_id,@Param("pobk_status")String pobk_status);


}