package com.konsonx.po;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table admin
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Admin {
    /** */
    private Integer admin_id;

    /** */
    private String admin_account;

    /** */
    private String admin_password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_id
     *
     * @return the value of admin.admin_id
     *
     * @mbg.generated
     */
    public Integer getAdmin_id() {
        return admin_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_id
     *
     * @param admin_id the value for admin.admin_id
     *
     * @mbg.generated
     */
    public void setAdmin_id(Integer admin_id) {
        this.admin_id = admin_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_account
     *
     * @return the value of admin.admin_account
     *
     * @mbg.generated
     */
    public String getAdmin_account() {
        return admin_account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_account
     *
     * @param admin_account the value for admin.admin_account
     *
     * @mbg.generated
     */
    public void setAdmin_account(String admin_account) {
        this.admin_account = admin_account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_password
     *
     * @return the value of admin.admin_password
     *
     * @mbg.generated
     */
    public String getAdmin_password() {
        return admin_password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_password
     *
     * @param admin_password the value for admin.admin_password
     *
     * @mbg.generated
     */
    public void setAdmin_password(String admin_password) {
        this.admin_password = admin_password;
    }
}