package com.konsonx.po;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table location
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Location {
    /** */
    private Integer location_id;

    /** */
    private String location_city;

    /** */
    private String location_district;

    /** */
    private String location_address;

    /** */
    private String location_alias;

    /** */
    private Integer location_yun_id;

    /** */
    private Integer location_amount;

    /** */
    private Integer location_available;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.location_id
     *
     * @return the value of location.location_id
     *
     * @mbg.generated
     */
    public Integer getLocation_id() {
        return location_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.location_id
     *
     * @param location_id the value for location.location_id
     *
     * @mbg.generated
     */
    public void setLocation_id(Integer location_id) {
        this.location_id = location_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.location_city
     *
     * @return the value of location.location_city
     *
     * @mbg.generated
     */
    public String getLocation_city() {
        return location_city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.location_city
     *
     * @param location_city the value for location.location_city
     *
     * @mbg.generated
     */
    public void setLocation_city(String location_city) {
        this.location_city = location_city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.location_district
     *
     * @return the value of location.location_district
     *
     * @mbg.generated
     */
    public String getLocation_district() {
        return location_district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.location_district
     *
     * @param location_district the value for location.location_district
     *
     * @mbg.generated
     */
    public void setLocation_district(String location_district) {
        this.location_district = location_district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.location_address
     *
     * @return the value of location.location_address
     *
     * @mbg.generated
     */
    public String getLocation_address() {
        return location_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.location_address
     *
     * @param location_address the value for location.location_address
     *
     * @mbg.generated
     */
    public void setLocation_address(String location_address) {
        this.location_address = location_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.location_alias
     *
     * @return the value of location.location_alias
     *
     * @mbg.generated
     */
    public String getLocation_alias() {
        return location_alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.location_alias
     *
     * @param location_alias the value for location.location_alias
     *
     * @mbg.generated
     */
    public void setLocation_alias(String location_alias) {
        this.location_alias = location_alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.location_yun_id
     *
     * @return the value of location.location_yun_id
     *
     * @mbg.generated
     */
    public Integer getLocation_yun_id() {
        return location_yun_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.location_yun_id
     *
     * @param location_yun_id the value for location.location_yun_id
     *
     * @mbg.generated
     */
    public void setLocation_yun_id(Integer location_yun_id) {
        this.location_yun_id = location_yun_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.location_amount
     *
     * @return the value of location.location_amount
     *
     * @mbg.generated
     */
    public Integer getLocation_amount() {
        return location_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.location_amount
     *
     * @param location_amount the value for location.location_amount
     *
     * @mbg.generated
     */
    public void setLocation_amount(Integer location_amount) {
        this.location_amount = location_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.location_available
     *
     * @return the value of location.location_available
     *
     * @mbg.generated
     */
    public Integer getLocation_available() {
        return location_available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.location_available
     *
     * @param location_available the value for location.location_available
     *
     * @mbg.generated
     */
    public void setLocation_available(Integer location_available) {
        this.location_available = location_available;
    }
}