package com.konsonx.po;

import com.alibaba.fastjson.annotation.JSONField;
import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table order
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Order {
    /** */
    private Integer order_id;

    /** */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    private Date order_finish_time;

    /** */
    private Integer order_user_id;

    /** */
    private Integer order_lent_location_id;

    /** */
    private Integer order_pobk_id;

    /** */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    private Date order_create_time;

    /** */
    private Integer order_has_finished;

    /** */
    private Integer order_revert_location_id;

    /** */
    private Float order_cost;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_id
     *
     * @return the value of order.order_id
     *
     * @mbg.generated
     */
    public Integer getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_id
     *
     * @param order_id the value for order.order_id
     *
     * @mbg.generated
     */
    public void setOrder_id(Integer order_id) {
        this.order_id = order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_finish_time
     *
     * @return the value of order.order_finish_time
     *
     * @mbg.generated
     */

    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    @JSONField(format ="yyyy-MM-dd HH:mm:ss" )
    public Date getOrder_finish_time() {
        return order_finish_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_finish_time
     *
     * @param order_finish_time the value for order.order_finish_time
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    @JSONField(format ="yyyy-MM-dd HH:mm:ss" )
    public void setOrder_finish_time(Date order_finish_time) {
        this.order_finish_time = order_finish_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_user_id
     *
     * @return the value of order.order_user_id
     *
     * @mbg.generated
     */
    public Integer getOrder_user_id() {
        return order_user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_user_id
     *
     * @param order_user_id the value for order.order_user_id
     *
     * @mbg.generated
     */
    public void setOrder_user_id(Integer order_user_id) {
        this.order_user_id = order_user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_lent_location_id
     *
     * @return the value of order.order_lent_location_id
     *
     * @mbg.generated
     */
    public Integer getOrder_lent_location_id() {
        return order_lent_location_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_lent_location_id
     *
     * @param order_lent_location_id the value for order.order_lent_location_id
     *
     * @mbg.generated
     */
    public void setOrder_lent_location_id(Integer order_lent_location_id) {
        this.order_lent_location_id = order_lent_location_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_pobk_id
     *
     * @return the value of order.order_pobk_id
     *
     * @mbg.generated
     */
    public Integer getOrder_pobk_id() {
        return order_pobk_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_pobk_id
     *
     * @param order_pobk_id the value for order.order_pobk_id
     *
     * @mbg.generated
     */
    public void setOrder_pobk_id(Integer order_pobk_id) {
        this.order_pobk_id = order_pobk_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_create_time
     *
     * @return the value of order.order_create_time
     *
     * @mbg.generated
     */

    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    @JSONField(format ="yyyy-MM-dd HH:mm:ss" )
    public Date getOrder_create_time() {
        return order_create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_create_time
     *
     * @param order_create_time the value for order.order_create_time
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    @JSONField(format ="yyyy-MM-dd HH:mm:ss" )
    public void setOrder_create_time(Date order_create_time) {
        this.order_create_time = order_create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_has_finished
     *
     * @return the value of order.order_has_finished
     *
     * @mbg.generated
     */
    public Integer getOrder_has_finished() {
        return order_has_finished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_has_finished
     *
     * @param order_has_finished the value for order.order_has_finished
     *
     * @mbg.generated
     */
    public void setOrder_has_finished(Integer order_has_finished) {
        this.order_has_finished = order_has_finished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_revert_location_id
     *
     * @return the value of order.order_revert_location_id
     *
     * @mbg.generated
     */
    public Integer getOrder_revert_location_id() {
        return order_revert_location_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_revert_location_id
     *
     * @param order_revert_location_id the value for order.order_revert_location_id
     *
     * @mbg.generated
     */
    public void setOrder_revert_location_id(Integer order_revert_location_id) {
        this.order_revert_location_id = order_revert_location_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_cost
     *
     * @return the value of order.order_cost
     *
     * @mbg.generated
     */
    public Float getOrder_cost() {
        return order_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_cost
     *
     * @param order_cost the value for order.order_cost
     *
     * @mbg.generated
     */
    public void setOrder_cost(Float order_cost) {
        this.order_cost = order_cost;
    }
}