package com.konsonx.po;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pobk
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Pobk {
    /** */
    private Integer pobk_id;

    /** */
    private Integer pobk_location_id;

    /** 'lent','available'*/
    private String pobk_status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pobk.pobk_id
     *
     * @return the value of pobk.pobk_id
     *
     * @mbg.generated
     */
    public Integer getPobk_id() {
        return pobk_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pobk.pobk_id
     *
     * @param pobk_id the value for pobk.pobk_id
     *
     * @mbg.generated
     */
    public void setPobk_id(Integer pobk_id) {
        this.pobk_id = pobk_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pobk.pobk_location_id
     *
     * @return the value of pobk.pobk_location_id
     *
     * @mbg.generated
     */
    public Integer getPobk_location_id() {
        return pobk_location_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pobk.pobk_location_id
     *
     * @param pobk_location_id the value for pobk.pobk_location_id
     *
     * @mbg.generated
     */
    public void setPobk_location_id(Integer pobk_location_id) {
        this.pobk_location_id = pobk_location_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pobk.pobk_status
     *
     * @return the value of pobk.pobk_status
     *
     * @mbg.generated
     */
    public String getPobk_status() {
        return pobk_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pobk.pobk_status
     *
     * @param pobk_status the value for pobk.pobk_status
     *
     * @mbg.generated
     */
    public void setPobk_status(String pobk_status) {
        this.pobk_status = pobk_status;
    }
}