package com.konsonx.po;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class User {
    /** */
    private Integer user_id;

    /** */
    private String user_phone;

    private String user_alias;

    /** */
    private String user_password;

    /** */
    private Float user_balance;



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     *
     * @mbg.generated
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id
     *
     * @param user_id the value for user.user_id
     *
     * @mbg.generated
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_phone
     *
     * @return the value of user.user_phone
     *
     * @mbg.generated
     */
    public String getUser_phone() {
        return user_phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_phone
     *
     * @param user_phone the value for user.user_phone
     *
     * @mbg.generated
     */
    public void setUser_phone(String user_phone) {
        this.user_phone = user_phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_password
     *
     * @return the value of user.user_password
     *
     * @mbg.generated
     */
    public String getUser_password() {
        return user_password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_password
     *
     * @param user_password the value for user.user_password
     *
     * @mbg.generated
     */
    public void setUser_password(String user_password) {
        this.user_password = user_password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_balance
     *
     * @return the value of user.user_balance
     *
     * @mbg.generated
     */
    public Float getUser_balance() {
        return user_balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_balance
     *
     * @param user_balance the value for user.user_balance
     *
     * @mbg.generated
     */
    public void setUser_balance(Float user_balance) {
        this.user_balance = user_balance;
    }

    public String getUser_alias() {
        return user_alias;
    }

    public void setUser_alias(String user_alias) {
        this.user_alias = user_alias;
    }
}